### ISSUE TITLE
remove recommendation

### ISSUE THREAD

**Issue by sunnysideup** [innowebau/silverstripe-remove-trailing-slash#1]
This will break your site in lots of places so I would remove that recommendation. 

```php

    public function RelativeLink($action = null)
    {
    	$link = parent::RelativeLink($action);
    	$link = rtrim($link, '/');
    	return $link;
    }
```

happy to explain in more detail over email / phone.

**Comment by xini** [comment]
This is not a recommendation, it's the main code of this module.

What exactly breaks on your site? I have this in production on all of my sites without issues.

**Comment by sunnysideup** [comment]
a. old page (in Versions) redirects to new page.
b. url contains actions ... e.g. `myoldpage/dosomething/12`
c. redirection now goes `mynewpagedosomething/12`.
